spring.application.name=api-gateway

server.port=${PORT:8080}

eureka.client.service-url.defaultZone=https://e-commerce-backend-microservices-production.up.railway.app/eureka/
eureka.instance.prefer-ip-address=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=20

jwt.secret=${JWT_SECRET}

spring.cloud.gateway.routes[0].id=authservice
spring.cloud.gateway.routes[0].uri=lb://AUTHSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/authservice/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
spring.cloud.gateway.default-filters[1]=AddResponseHeader=Access-Control-Expose-Headers,Authorization

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true