spring.application.name=authservice

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://localhost:3306/authservice
spring.datasource.username=${db-username}
spring.datasource.password=${db-password}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${email}
spring.mail.password=${email-password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=${JWT_SECRET}

spring.security.oauth2.client.registration.google.client-id=${google-client-id}
spring.security.oauth2.client.registration.google.client-secret=${google-client-secret}
spring.security.oauth2.client.registration.google.scope=openid,email,profile
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
server.forward-headers-strategy=framework
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8765/authservice/login/oauth2/code/google
spring.security.oauth2.client.registration.google.client-name=Google

spring.security.oauth2.client.registration.amazon.client-id=${amazon-client-id}
spring.security.oauth2.client.registration.amazon.client-secret=${amazon-client-secret}
spring.security.oauth2.client.registration.amazon.scope=profile
spring.security.oauth2.client.registration.amazon.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.amazon.redirect-uri=http://localhost:8765/authservice/login/oauth2/code/amazon
spring.security.oauth2.client.registration.amazon.client-name=Amazon

spring.security.oauth2.client.provider.amazon.authorization-uri=https://www.amazon.com/ap/oa
spring.security.oauth2.client.provider.amazon.token-uri=https://api.amazon.com/auth/o2/token
spring.security.oauth2.client.provider.amazon.user-info-uri=https://api.amazon.com/user/profile
spring.security.oauth2.client.provider.amazon.user-name-attribute=user_id