spring.application.name=comment

server.port=8060

spring.mongodb.uri=mongodb://localhost:27017/comment-db
spring.mongodb.database=comment-db
spring.data.mongodb.auto-index-creation=true

jwt.secret=${JWT_SECRET}