spring.application.name=cart-service

server.port=8070

spring.mongodb.uri=mongodb://localhost:27017/cart-db
spring.mongodb.database=cart-db
spring.data.mongodb.auto-index-creation=true

jwt.secret=${JWT_SECRET}